apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce
  namespace: mini-mesh
  labels:
    app: ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ce
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ce
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: ce
          image: mini-mesh/ce:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mini-mesh-config
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
