// We specify the version of the Protobuf language we are using. proto3 is the modern standard.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: minimesh/v1/telemetry.proto

// The package name prevent naming collisions

package minimeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryPayload represents the health metrics of a specific Edge node.
type TelemetryPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the machine sending the data
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Unix timestamp of when the metrics were collected
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// CPU utilization percentage
	CpuPercent float64 `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// Memory metrics
	TotalMemMb    uint64  `protobuf:"varint,4,opt,name=total_mem_mb,json=totalMemMb,proto3" json:"total_mem_mb,omitempty"`
	UsedMemMb     uint64  `protobuf:"varint,5,opt,name=used_mem_mb,json=usedMemMb,proto3" json:"used_mem_mb,omitempty"`
	MemPercent    float64 `protobuf:"fixed64,6,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_minimesh_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_minimesh_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_minimesh_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryPayload) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *TelemetryPayload) GetTotalMemMb() uint64 {
	if x != nil {
		return x.TotalMemMb
	}
	return 0
}

func (x *TelemetryPayload) GetUsedMemMb() uint64 {
	if x != nil {
		return x.UsedMemMb
	}
	return 0
}

func (x *TelemetryPayload) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

// This is empty because CE does not need response from the RE
type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_minimesh_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minimesh_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_minimesh_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

var File_minimesh_v1_telemetry_proto protoreflect.FileDescriptor

const file_minimesh_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1bminimesh/v1/telemetry.proto\x12\vminimesh.v1\"\xcd\x01\n" +
	"\x10TelemetryPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12 \n" +
	"\ftotal_mem_mb\x18\x04 \x01(\x04R\n" +
	"totalMemMb\x12\x1e\n" +
	"\vused_mem_mb\x18\x05 \x01(\x04R\tusedMemMb\x12\x1f\n" +
	"\vmem_percent\x18\x06 \x01(\x01R\n" +
	"memPercent\"\x13\n" +
	"\x11TelemetryResponse2f\n" +
	"\x10TelemetryService\x12R\n" +
	"\x0fStreamTelemetry\x12\x1d.minimesh.v1.TelemetryPayload\x1a\x1e.minimesh.v1.TelemetryResponse(\x01B%Z#mini-mesh/pb/minimesh/v1;minimeshv1b\x06proto3"

var (
	file_minimesh_v1_telemetry_proto_rawDescOnce sync.Once
	file_minimesh_v1_telemetry_proto_rawDescData []byte
)

func file_minimesh_v1_telemetry_proto_rawDescGZIP() []byte {
	file_minimesh_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_minimesh_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_minimesh_v1_telemetry_proto_rawDesc), len(file_minimesh_v1_telemetry_proto_rawDesc)))
	})
	return file_minimesh_v1_telemetry_proto_rawDescData
}

var file_minimesh_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_minimesh_v1_telemetry_proto_goTypes = []any{
	(*TelemetryPayload)(nil),  // 0: minimesh.v1.TelemetryPayload
	(*TelemetryResponse)(nil), // 1: minimesh.v1.TelemetryResponse
}
var file_minimesh_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: minimesh.v1.TelemetryService.StreamTelemetry:input_type -> minimesh.v1.TelemetryPayload
	1, // 1: minimesh.v1.TelemetryService.StreamTelemetry:output_type -> minimesh.v1.TelemetryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_minimesh_v1_telemetry_proto_init() }
func file_minimesh_v1_telemetry_proto_init() {
	if File_minimesh_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minimesh_v1_telemetry_proto_rawDesc), len(file_minimesh_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minimesh_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_minimesh_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_minimesh_v1_telemetry_proto_msgTypes,
	}.Build()
	File_minimesh_v1_telemetry_proto = out.File
	file_minimesh_v1_telemetry_proto_goTypes = nil
	file_minimesh_v1_telemetry_proto_depIdxs = nil
}
