// We specify the version of the Protobuf language we are using. proto3 is the modern standard.
syntax = "proto3";

// The package name prevent naming collisions
package minimesh.v1

// This tells the complier where to put the generated Go code, and what to name the Go package
option go_package = "mini-mesh/pb/minimesh/v1;minimesh_v1";

// TelemetryPayload represents the health metrics of a specific Edge node.
message TelemetryPayload {
  // The unique identifier for the machine sending the data
  string node_id = 1;
  
  // Unix timestamp of when the metrics were collected
  int64 timestamp = 2;
  
  // CPU utilization percentage
  double cpu_percent = 3;
  
  // Memory metrics
  uint64 total_mem_mb = 4;
  uint64 used_mem_mb = 5;
  double mem_percent = 6;
}

// This is empty because CE does not need response from the RE
message TelemetryResponse = {}

// TelemetryService defines the RPCs (Remote Procedure Calls) available.
service TelemetryService {
    // StreamTelemetry allows the CE to open a persistent connection and stream payloads.
    // Notice the 'stream' keyword - this makes it an asynchronous pipe, not a single request/response.
    rpc StreamTelemetry(stream TelemetryPayload) returns (TelemetryResponse);
}